# About the project

After learning online course from the Data Camp, I think all the programming languages are essentially the same. R is very similar to Python, and some functions are just like one the the Python library (Pandas), since they all use Dataframe object to store information, so I find it very easy to understand, and I think R is focused on the data processing where as Python is more of general purpose type of language.

My github repository is [here](https://github.com/gpx135/IODS-project).

My course diary web page is [here](https://gpx135.github.io/IODS-project/).


Some notes about the R language:
- R is an open source language which mean free of charge and everyone can use it. In the field of statistical analysis, it is very convienient to manipulate the data. R's basic data types are character, numeric, integer, complex, and logical. R's basic data structures include the vector, list, matrix, data frame, and factors.


- assign a value:
```R
something <- value
```

- add comment
```R
# some_comment (just like python)
```

- execute a line of code (just like debug mode but not entirely the same)
```R
Cmd/ctrl + Enter
```

- basic arithmetics
```R
+ # Addition
- # Subtraction
* # Multiplication
/ # Division
^ (or **) # Exponentiation
```

- excecute a function
```R
some_function(object)
```

- take mean value
```R
mean(data_source)
```

- access first a lines of dataframe
```R
head(students2014, n = a)
# its a good practice to add the argument name to avoid confusion
```


- structure of data
```R
str(data_source)
# but in python it prints out string of an object
```

- data types: numeric, characters, logical, factor(new concept conpared to python)
```R
"Strongly disagree" = 1
"Strongly agree" = 5
```

```R
# Boolean values: TRUE or FALSE 
# all upper case
```

- create a vactor
```R
c(2, 3, 4.1, 5) # has to be same data type

```


- summary of the data
```R
summary(data source)
# it will return some important statistical value of the selected data
```

- plot a scatter figure
```R
plot(x, y, "p", main = "some title")
```

- manupulate a value of a vector
```R
names[1]
# start at 1 not 0
names[1] <- "new_value"
names[c(1, 3)] # select value from these positions, order matters
```


- create a integer vector
```R
c[1, 2, 3, 4, 5]
1:5

# manupulate the vector
(1:5)*2

# length of the data
length(data)

slicing
data[begin:end]
# possible to modify the vector when slicing a dataframe
```

- logical comparison

```R
==	# exactly equal to
!=	# not equal to
<	# less than
>	# greater than
<=	# less or equal to
>=	# greater or equal to
!a	# NOT a
a & b	# a AND b
a | b	# a OR b
```

- take sebset of the dataframe
```R
subset(data_source, conditions...)

```

- looping
```R
for (counter in vector) {
  commands
  more commands
}
```
- access a library
```R


- create functions
```R
function_name <- function(arg1, arg2 = 5) return(return_value) # arg = default value
```